// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnuVSNL2jm6rsF9xnilVkotDAvuJj1v8A',
    appId: '1:599219594280:web:202578136df2db5aab011d',
    messagingSenderId: '599219594280',
    projectId: 'whatsbytes-task',
    authDomain: 'whatsbytes-task.firebaseapp.com',
    storageBucket: 'whatsbytes-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJPXr0z7zSswBA_qvWaBF6ABDfBNKaWrk',
    appId: '1:599219594280:android:6bad125cc8fcd417ab011d',
    messagingSenderId: '599219594280',
    projectId: 'whatsbytes-task',
    storageBucket: 'whatsbytes-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZsbeDBb1uroCir-4Zy3TAybDeXcReEY',
    appId: '1:599219594280:ios:fb4049604bee4f2eab011d',
    messagingSenderId: '599219594280',
    projectId: 'whatsbytes-task',
    storageBucket: 'whatsbytes-task.firebasestorage.app',
    iosBundleId: 'com.example.whatbytesTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIZsbeDBb1uroCir-4Zy3TAybDeXcReEY',
    appId: '1:599219594280:ios:fb4049604bee4f2eab011d',
    messagingSenderId: '599219594280',
    projectId: 'whatsbytes-task',
    storageBucket: 'whatsbytes-task.firebasestorage.app',
    iosBundleId: 'com.example.whatbytesTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnuVSNL2jm6rsF9xnilVkotDAvuJj1v8A',
    appId: '1:599219594280:web:acd8f63554addb9eab011d',
    messagingSenderId: '599219594280',
    projectId: 'whatsbytes-task',
    authDomain: 'whatsbytes-task.firebaseapp.com',
    storageBucket: 'whatsbytes-task.firebasestorage.app',
  );
}
